# Generated by Django 4.1.4 on 2022-12-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forklift',
            name='next_check',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
