# Generated by Django 4.1.4 on 2024-07-03 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0002_forklift_next_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('pid', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reparatur',
            fields=[
                ('rid', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('schadeneintritt', models.DateTimeField()),
                ('fertigstellung', models.DateTimeField()),
                ('forkliftid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forklift.forklift')),
                ('reparaturid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forklift.partner')),
            ],
        ),
    ]
