# Generated by Django 5.0.6 on 2024-07-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0003_partner_reparatur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparatur',
            old_name='reparaturid',
            new_name='partnerid',
        ),
        migrations.AlterField(
            model_name='reparatur',
            name='fertigstellung',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reparatur',
            name='schadeneintritt',
            field=models.TextField(),
        ),
    ]
